# a=2
# b=4
# print(a+b)
# print("saurav")

# 3
# name= input("name:-")
# age= input("age:-")
# print(name , "\n", age)

           
#  name= input("name:-")
#  age=int(input("age:-"))
#  marks=int(input("marks:-") )
# print(marks,"\n",name,"\n",age)       



# name= str(input("name:-"))
# age=int(input("age"))
#  num_age=int(age)
# print(name,"\n", age)
# print(num_age  +5)

# a=10
# print()


# #adding integer
# x=5
# x=int(x)
# print(x)



# #adding float
# x=4
# x=float(x)
# print(x)



# #converting float to integer
# x=4.5
# x=int(x)
# print(X)


















# x={12,13,14,15}
# y={14,15,16,18}
# z=x.union(y)
# print(z)
# new=x.symmetric_difference(y)
# print(new)
# old=x.difference(y)
# print(old)
# mid=x.intersection(y)
# print(mid)


# x=int(input("n1:"))                          #arithematic operators
# y=int(input("n2:"))
# print(x+y)
# print(x*y)
# print(x-y)
# print(x/y)
# print(x%y)


# a=35                                          #comparison operator
# e=23
# print("tarun" is name)
# print(23 is not age )
# i= [12,15,18,"orange" l, "apples"]
# x= ["saurav", "tarun"]
# print(li)
# print(li[4])
# print(li[::-1])
# print(li[0:3])
# li.append("banana")
# li.insert( 3 , 37)
# li.extend(x)
# print(li)

# b=36
# print(a<b)
# print(a>b)
# print(a<=b)
# print(a>=b)
# print(a==b)


# a=["tarun","saurav","aman","karan"]              #membership operator
# print("tarun" in a)
# print("saurav" not in a)

# ax=[12,13,141,15]
# print(12 in ax)
# print(141 not in ax)

name="tarun"                                        #identity opera

# s = "Aman
# print(s.title())
# print(s.endswith(".exe"))
# print(s.isalnum())
# print(s.isalpha())
# print(s.isascii())
# print(s.isdecimal())
# print(s.isdigit())
# print(s.islower())
# print(s.isnumeric())
#  print(s.isspace())
# print(s.isupper())
# print(s.lower())
# print(len(s))

# n= int(input("enter your number-"))
# if n%2==1:

#     print("n is an odd number")
# else:
#     print("n is not an odd number")




# age=int(input("enter your age"))
# if age<20:
#     print("child")
# elif (12<age>30):
#     print("teenager")
# elif (50<age>100)
#     print("old")
# elif (100<age>200):
#      print("immortal"()            
#  else:


 












#  li=[]
# n =input()
# li.appenLId(n)
# print(li)
 
 










# # Positive, Negative, or Zero Check
# number = int(input("Enter a number: "))

# if number > 0:
#     print("The number is Positive")
# elif number < 0:
#     print("The number is Negative")
# else:
#     print("The number is Zero")


# # Even or Odd Check
# if number % 2 == 0:
#     print("The number is Even")
# else:
#     print("The number is Odd")










# Voting Eligibility

# age = int(input("Enter your age: "))

# if age >= 18:
#     print("Eligible to vote.")
# else:
#     print("Not eligible.")


 


# Maximum of Two Numbers

# num1 = int(input("Enter first number: "))
# num2 = int(input("Enter second number: "))

# if num1 > num2:
#     print("The larger number is:", num1)
# elif num2 > num1:
#     print("The larger number is:", num2)
# else:
#     print("Both numbers are equal.")



# Student Grading System

# score = int(input("Enter student's score (0-100): "))

# if score >= 90:
#     print("Grade: A")
# elif rscore >= 80:
#     print("Grade: B")
# elif score >= 70:
#     print("Grade: C")
# else:
#     print("Grade: F")



# Leap Year Calculator

# year = int(input("Enter a year: "))

# if year % 400 == 0:
#     print("It is a Leap Year.")
# elif year % 100 == 0:
#     print("It is not a Leap Year.")
# elif year % 4 == 0:
#     print("It is a Leap Year.")
# else:
#     print("It is not a Leap Year.")




# Traffic Light Simulator

# color = input("Enter traffic light color: ")

# if color == "red":
#     print("Stop")
# elif color == "yellow":
#     print("Caution")
# elif color == "green":
#     print("Go")
# else:
#     print("Invalid color")





# BMI Classifier

# weight = float(input("Enter your weight in kg: "))
# height = float(input("Enter your height in meters: "))

# bmi = weight / (height * height)

# print("Your BMI is:", round(bmi, 2))

# if bmi < 18.5:
#     print("Category: Underweight")
# elif bmi < 25:
#     print("Category: Normal")
# elif bmi < 30:
#     print("Category: Overweight")
# else:
#     print("Category: Obese")







#nested if
# a  = int(input("enter ur attendence out of 100 :"))
# s  = int(input("enter ur marks in assignement out of 10 :"))
# mst  = int(input("enter ur mst marks out of 100 :"))
# exam = input("enter y/n :")
# if exam == "y":
#     exam= True
# else :
#      exam = False
# if a>75:
#     if s>6 :
#         if mst>33:
#                   if exam is True:
#                       print("pass")
#                   else:
#                        print("fail")
#         else:
#              print("mst not clear")
#     else:
#          print("assignment not completed")
# else: 
#     print("not eligible")                 



#looping statement
# age="50"
# for i in (age):
#           print(i)

# for i in range(50):
#         print(i)
# for i in range(1,10,2):
#         print(i) 
# for i in range(2,10,1):
#         print(i) 
# for i in range(0,200):
#         print(i)                    
          
                
          

#while loop
# i=0
# while<=10:
#     print(i)
#     i+=1






# marks=[57,63,59,75,49]
# sum=0
# for i in marks:
#     sum= sum+ i
# print(sum)    

# count=0
# s =("vampire")
# vowels=["a","e", "i", "o","u"]
# for i in s.lower():
#     #print()
#     if i in vowels:
#         count= count + 1
# print(count)





# li=[]
# l = int(input("enter length of list:"))
# while l >=0:
#        el = input("enter item: ")
#        li.append(el)
#        l-=1
# print(li)       
         
 
# for i in range(20):
#         if i==16:
#                 continue 
#         print(i)    


# for i in range(20):
#     if i==15:
#              break
#     print(i)   
# switch and case
# day= int(input("day:-"))
# match day :
#         case 1:
#                 print("monday")
#         case 2:
#                 print("tuesay")
#         case 3:
#                 print("wednesday")
#         case 4:
#                 print("thursday")
#         case 5:
#                 print("friday")
#         case 6:
#                 print("saturday")
#         case 7:  
#                 print("sunday")
#         case _:
#                 print("invalid")     


# i=0
# while i<=10:
#         if i==5:
#             break
#         else:
#               print(i)
#               i+=1    


 


#              *
#             **
#            ***
#           ****
#          *****
#         ****** 
#        *******
#       ********
#      *********
# rows=10
# for i in range(1,rows+1):
#         print(" "*(row-i)+"*"*(i-1)
                   
       


# *********
#  ********
#   *******
#    ******
#     *****
#      ****
#       ***
#        **
#          *  


# rows=10
# for i in range(1,rows+1):
#     print(" "*(i-1)+"*"*(rows-i))










# row = 100
# columns = 100
# for i in range(row):
#      print("*" * columns)    



#calculator 
# simulator



# num1 = float(input("Enter first number: "))
# num2 = float(input("Enter second number: "))
# operator = input("Enter operator (+, -, *, /): ")

# if operator == "+":
#     result = num1 + num2
#     print("Result:", result)

# elif operator == "-":
#     result = num1 - num2
#     print("Result:", result)

# elif operator == "*":
#     result = num1 * num2
#     print("Result:", result)

# elif operator == "/":
#     if num2 != 0:
#         result = num1 / num2
#         print("Result:", result)
#     else:
#         print("Cannot divide by zero")

# else:
#     print("invalid operator")

                  


# #multiplication 
# num = int(input("enter a number: "))

# for i in range(1,11):
#       print(num,"*", i, "=", num * i)  




#program for calculate shopping bills
 

# prices = []

# for i in range(5):
#     price = float(input("Enter price of item " + str(i + 1) + ": "))
#     prices.append(price)

# total = sum(prices)

# if total >= 2000:
#     discount = total * 0.10

# elif total >= 1000:
#     discount = total * 0.05

# else:
#     discount = 0

# final_bill = total - discount

# print("\n----- SHOPPING BILL -----")
# print("Prices:", prices)
# print("Total Bill: ₹", total)
# print("Discount: ₹", discount)
# print("Final Bill: ₹", final_bill)



#list marks analyzing 

# # List containing marks of 10 students
# marks = [78, 92, 65, 88, 45, 76, 95, 56, 81, 69]

# # Print all marks using a loop
# print("All Student Marks:")

# for mark in marks:
#     print(mark)

# # Find the highest mark
# highest = marks[0]

# for mark in marks:
#     if mark > highest:
#         highest = mark

# # Find the lowest mark
# lowest = marks[0]

# for mark in marks:
#     if mark < lowest:
#         lowest = mark

# # Print highest and lowest marks
# print("\nHighest Mark:", highest)
# print("Lowest Mark:", lowest)

# # Print first three marks using slicing
# print("\nFirst Three Marks:", marks[:3])

# # Print last three marks using slicing
# print("Last Three Marks:", marks[-3:])



#functions

# def add(x , y):
#     z= x+y
#     return z

# n1 = int(input())
# n2 = int(input())
# print(add(n1 , n2))   



# # n= 0-100
# for i in range (101):
#     if i%3==0:
#         print("fizz")
#     elif i%5==0:
#         print("buzz")
#     elif i%3==0 and i%5==0:
#         print("fizzbuzz")
#     else:
#         print(i)
           
# def fb(r):
#     for i in range (r):
#         if i%3==0:
#             print("fizz")
#         elif i%5==0:
#             print("buzz")
#         elif i%3==0 and i%5==0:
#             print("fizzbuzz")
#         else:
#             print(i)
#     return "thanks"

# user = int(input("enter range for checking : "))
# print(fb(user))   


# n= int(input("enter your number"))
# li=[]
# for i in range (1,n+1):
#      if n%i==0:
#       li.append(i)
# print(li)
       


# def fact(n):                                #factoril with fucntion
#    li=[]   
#    for i in range (1,n+1):
#         if n%i==0:
#          li.append(i)
#    return li
# n= int(input("enter your number:"))
# print(fact(n))






# num1 = float(input("Enter first number: "))
# num2 = float(input("Enter second number: "))
# operator = input("Enter operator (+, -, *, /): ")

# if operator == "+":
#     result = num1 + num2
#     print("Result:", result)

# elif operator == "-":
#     result = num1 - num2
#     print("Result:", result)

# elif operator == "*":
#     result = num1 * num2
#     print("Result:", result)

# elif operator == "/":
#     if num2 != 0:
#         result = num1 / num2
#         print("Result:", result)
#     else:
#         print("Cannot divide by zero")

# else:
#     print("invalid operator")




# def cal(num1,num2):
#     if operator == "+":
#         result = num1 + num2
#         print("Result:", result)
#     elif operator == "-":
#         result = num1 - num2
#         print("Result:", result)

#     elif operator == "*":
#         result = num1 * num2
#         print("Result:", result)

#     elif operator == "/":
#         result = num1 / num2
#         print("Result:", result)
    
#     else:
#         print("invalid operator")   

#     return "thnx"
# num1 = float(input("enter your first number:"))
# num2 = float(input("enter your second number:"))
# operator = input("Enter operator (+, -, *, /): ")
# print (cal(num1,num2))


#positional arguments

# def frnds(*x):
#     print("my name is ", x[0])
#     for i in x[1:]:
#         print(i , "is my good friend .")
#     return "my"
    
# print(frnds("kamal", "parwnder","aman","krn"))          


#add numbers

# def add(*x):
#     sum=0
#     for i in x:
#         sum = i+sum
#     return sum
# print(add(10,20,30,40))   
    

#kwargs argument

# def kw(**x):
#     for i,j in x.items():
#         print(i , j)   #[]0,1,2 for indexing
              
#     return "data representation"
# print(kw(name =["aman", "tarun", "saurav"] ,
#          course = ["DA" ,"AI","DS"] ,
#          id =[101, 102, 103]))  


# def build_profile(**x):
#     for i,j in x.items():
#         print(i,j) 

#     return "data is represented"
# print(build_profile(name =["thor", "hulk", "sukuna"] ,
#                    occupation =["avenger", "fighter","demon"] ,
#                    age =[30,40,50]))
                    
             

# def std(username ,*scores):
#     print("username:", username) 
#     print("scores:", scores)
#     return "data is repsented"
# print(std("saurav",40,50,60))    




# li=[20,30,40,50]
# bd=list(map (lambda x :x*2, li))
# print(bd)


# li= (5,10,15,20)
# bd=tuple(filter(lambda x:x%2==0 ,li))
# print(bd)


#lanbda sort



# names=["naruto", "demon slayer", "death note", "attack on titan"]
# gd=sorted(names, reverse= True , key=lambda x:len(x))
# print(gd)
# gn=sorted(names, reverse= False , key=lambda x: len(x))
# print(gn)


# nested=[[1,2],[2,4,6],[8,4,1]]
# from functools import reduce
# rr=set(reduce(lambda x,y : x+y , nested))
# rr1=list(reduce(lambda x,y : x+y , nested))
# print(rr)
# print(rr1) 





#even or odd
# n=int(input("enter a number "))
# check = lambda x: "even" if x%2==0 else "odd"

# print(check(10))


#SORTING BY DICTIONARY VALUES

# marks = {"saurav":50, "tarun":60, "aman":70, "vicky":80}
# result = dict(sorted(marks.items(), key=lambda x: x[1]))
# print(result)
              


# marks = {"saurav":50, "tarun":60, "aman":70, "vicky":80}
# result = dict(sorted(marks.items(), key=lambda x: x[1], reverse=True))
# print(result)
              



# def deco(game):
#     def demo(*x , **y):
#         print("world shall know pain")

#         print(game(*x ,**y))

#         return "thanks"
#     return demo
    
# @deco
# def add(x , y):
#     return x+y
# print(add(45, 50))

#  @def      
# def subtract(x, y):
#    return x-y
# print(subtract(45, 70)


#decorator above'
# @deco
# def frnds(*x):
#     print("my name is ", x[0])
#     for i in x[1:]:
#         print(i , "is my good friend .")
#     return "my"
    
# print(frnds("kamal", "parwnder","aman","krn"))    



# class abc:
#     name = input()
#     age = input()
#     job = input()

# obj = abc()

# print(obj.job,obj.name)





# class abc:
#     name = input("enter name")
#     age = int(input("enter age "))
#     job = input("job type")
# obj = abc()

# print(obj.job,obj.name,obj.age)





# class abc:
#     name = "saurav"
#     age = 21
#     job = "CEO"
# obj = abc()

# print(obj.job,obj.name,obj.age)



# class calc:
#     def add(self , *a ):
#         sum = 0
#         for i in a :
#             sum = sum+i
#         return sum


#     def sub(self ,x, y):
#         return x-y

# obj = calc()
# print(obj.add(10 , 20))

# class calc:
#     def add(self,a,b):
#         return a+b
#     def sub(self,a,b):
#         return a-b
#     def mult(self,a,b):
#         return a*b
#     def divi(self, a,b):
#         return a/b 

# obj = calc()
# print(obj.add(2,2),obj.sub(4,4),obj.mult(5,5),obj.divi(6,6))    



# class person:
#     name=input("enter your name:")
#     age=input("enter your age:")
#     subject=input("enter your subject")
# person1=person()
# print(person.name,person.age,person.subject)
# person2=person()
# person2.name=input("person2 enter your name:")
# person2.age=input("person2 enter your age:")
# person2.subject=input("person2 enter your subject:")
# print(person2.name,person2.age,person2.subject)                      





#vehicle information
# class vehicle:
#     type="car"
#     id= 87877438
#     wheels= 4
# vehicle1=vehicle()
# print(vehicle1.type,vehicle1.id,vehicle1.wheels)  
# vehicle2=vehicle()
# vehicle2.type=input("vehicle2 enter your vehicle type")
# vehicle2.id=input("vehicle2 enter your vehicle id")
# vehicle2.wheels=input("vehicle2 enter number of wheels")
# print(vehicle2.type,vehicle2.id,vehicle.wheels)



#construcor

# class vehicle:
#     def __init__(self , name , model , type ):
#         self.a = name
#         self.b = model
#         self.c = type
#         print("created")
#     def auto(self):
#         print("name of the bike is ", self.a , "model is",self.b , "its type is ", self.c)
#         return "chobar"        
# bike = vehicle("bmw" , 2026 , "ev")
# car = vehicle( "bentley" , 2025 , "diesel")
# print(bike.auto())
# print(car.auto())



#single in hheritance

# class person:
#     def __init__(self , fname , lname):
#         self.f = fname
#         self.l = lname
#     def printname(self):
#         print(self.f, self.l)
#         return "show"
# class student(person):
#     def __init__(self, grade, marks):
#         person.__init__(self, grade,marks)
#         super().__init__(self.f , self.l)
    
#     #we use person class to create object and hen execute the printname method

# x = person("alpha" , "sigma")
# print(x.printname())
# y = student("A" , 45)
# print(y.printname())


# class movie:
#     def __init__(self, name, release , genre):
#         self.n = name
#         self.r = release 
#         self.g = genre
#     def printname(self):
#         print(self.n, self.r , self.g)  
        
# class person(movie):
#     def __init__(self, type, review , rating):
#         person.__init__(self , type , review , rating)
#         super().__init__(self.n , self.r , self.g)

    
# x =movie( "dhurandhar" , 2026 , "action")
# print(x.printname())
# y = person("spy" , "must watch" , "A")
# print(y.printname())




#multiple inheritance

class Hospital:
    def __init__(self, hospital_name, hospital_city, hospital_type):
        self.a = hospital_name
        self.b = hospital_city
        self.c = hospital_type

    def details(self):
        return self.a, self.b, self.c


class Doctor(Hospital):
    def __init__(self, doctor_name, doctor_age, doctor_specialization):
        super().__init__("City Hospital", "Patiala", "Private")
        self.d = doctor_name
        self.e = doctor_age
        self.f = doctor_specialization

    def doctor_details(self):
        return self.d, self.e, self.f


class Surgeon(Doctor):
    def __init__(self, surgeon_name, surgeon_exp, surgeon_operations):
        super().__init__("Dr. Raj", "35", "Cardiologist")
        self.g = surgeon_name
        self.h = surgeon_exp
        self.i = surgeon_operations

    def surgeon_details(self):
        return self.g, self.h, self.i


t1 = Hospital("Apollo", "Delhi", "Private")
print(t1.details())

t2 = Doctor("Dr. Raj", "35", "Cardiologist")
print(t2.details())
print(t2.doctor_details())

t3 = Surgeon("Dr. Aman", "10 years", "500")
print(t3.details())
print(t3.doctor_details())
print(t3.surgeon_details())